#!/usr/bin/env node

/**
 * create-y-company — Interactive CLI to generate a company.yml
 *
 * Usage: npx ts-node cli/create-y-company.ts
 *   or:  node dist/cli/create-y-company.js
 *
 * Generates a valid company.yml matching the _y Holdings schema.
 * Uses only Node built-in readline — no external dependencies.
 */

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? ` (${defaultVal})` : '';
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

function askNumber(question: string, defaultVal: number): Promise<number> {
  return ask(question, String(defaultVal)).then((v) => {
    const n = parseInt(v, 10);
    return isNaN(n) ? defaultVal : n;
  });
}

function askChoice(question: string, choices: string[], defaultVal: string): Promise<string> {
  const choiceStr = choices.map((c) => (c === defaultVal ? `[${c}]` : c)).join(' / ');
  return ask(`${question} (${choiceStr})`, defaultVal).then((v) => {
    return choices.includes(v) ? v : defaultVal;
  });
}

// ── LLM Presets ──

const LLM_PRESETS: Record<string, Record<string, { type: string; model: string; label: string }>> = {
  'ollama-only': {
    primary: { type: 'ollama', model: 'qwen3:32b', label: 'Qwen3 32B' },
    secondary: { type: 'ollama', model: 'deepseek-r1:70b', label: 'DeepSeek R1 70B' },
    fast: { type: 'ollama', model: 'gemma3:12b', label: 'Gemma3 12B' },
  },
  'cloud-only': {
    primary: { type: 'anthropic', model: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
    secondary: { type: 'anthropic', model: 'claude-opus-4-20250514', label: 'Claude Opus 4' },
    fast: { type: 'gemini', model: 'gemini-2.5-flash', label: 'Gemini Flash' },
  },
  hybrid: {
    primary: { type: 'anthropic', model: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
    secondary: { type: 'ollama', model: 'deepseek-r1:70b', label: 'DeepSeek R1 70B' },
    fast: { type: 'ollama', model: 'qwen3:32b', label: 'Qwen3 32B' },
    vision: { type: 'gemini', model: 'gemini-2.5-flash', label: 'Gemini Flash' },
  },
};

// ── YAML Generator ──

function indent(level: number): string {
  return '  '.repeat(level);
}

function yamlString(val: string): string {
  if (/[:#{}[\],&*?|>!%@`]/.test(val) || val.startsWith('"') || val.startsWith("'")) {
    return `"${val.replace(/"/g, '\\"')}"`;
  }
  return val;
}

interface Department {
  id: string;
  name_ko: string;
  name_en: string;
  floor: number;
  short_ko: string;
  short_en: string;
}

interface Agent {
  id: string;
  number: string;
  name: string;
  tier: string;
  department: string;
  reportTo: string;
  llm: string;
  role: string;
  skills: string[];
}

function generateYaml(config: {
  companyName: string;
  mission: string;
  chairman: string;
  language: string;
  theme: string;
  llms: Record<string, { type: string; model: string; label: string }>;
  departments: Department[];
  agents: Agent[];
}): string {
  const lines: string[] = [];

  lines.push('# ============================================');
  lines.push(`# ${config.companyName} — Company Configuration`);
  lines.push('# ============================================');
  lines.push(`# Generated by create-y-company CLI`);
  lines.push(`# ${new Date().toISOString()}`);
  lines.push('# ============================================');
  lines.push('');
  lines.push('company:');
  lines.push(`${indent(1)}name: ${yamlString(config.companyName)}`);
  lines.push(`${indent(1)}mission: ${yamlString(config.mission)}`);
  lines.push(`${indent(1)}chairman: ${yamlString(config.chairman)}`);
  lines.push(`${indent(1)}language: ${config.language}`);
  lines.push(`${indent(1)}theme: ${config.theme}`);

  // LLMs
  lines.push('');
  lines.push('# ============================================');
  lines.push('# LLM Models');
  lines.push('# ============================================');
  lines.push('llms:');
  for (const [key, llm] of Object.entries(config.llms)) {
    lines.push(`${indent(1)}${key}:`);
    lines.push(`${indent(2)}type: ${llm.type}`);
    lines.push(`${indent(2)}model: ${llm.model}`);
    lines.push(`${indent(2)}label: ${yamlString(llm.label)}`);
  }

  // Departments
  lines.push('');
  lines.push('# ============================================');
  lines.push('# Departments');
  lines.push('# ============================================');
  lines.push('departments:');
  for (const dept of config.departments) {
    lines.push(`${indent(1)}- id: ${dept.id}`);
    lines.push(`${indent(2)}name_ko: ${yamlString(dept.name_ko)}`);
    lines.push(`${indent(2)}name_en: ${yamlString(dept.name_en)}`);
    lines.push(`${indent(2)}floor: ${dept.floor}`);
    lines.push(`${indent(2)}short_ko: ${yamlString(dept.short_ko)}`);
    lines.push(`${indent(2)}short_en: ${yamlString(dept.short_en)}`);
  }

  // Agents
  lines.push('');
  lines.push('# ============================================');
  lines.push('# Agents');
  lines.push('# ============================================');
  lines.push('agents:');
  for (const agent of config.agents) {
    lines.push(`${indent(1)}- id: ${agent.id}`);
    lines.push(`${indent(2)}number: "${agent.number}"`);
    lines.push(`${indent(2)}name: ${yamlString(agent.name)}`);
    lines.push(`${indent(2)}tier: ${agent.tier}`);
    lines.push(`${indent(2)}department: ${agent.department}`);
    lines.push(`${indent(2)}reportTo: ${agent.reportTo}`);
    lines.push(`${indent(2)}llm: ${agent.llm}`);
    lines.push(`${indent(2)}role: ${agent.role}`);
    lines.push(`${indent(2)}skills: [${agent.skills.join(', ')}]`);
  }

  // Decision Pipeline
  lines.push('');
  lines.push('# ============================================');
  lines.push('# Decision Pipeline');
  lines.push('# ============================================');
  lines.push('pipelines:');
  lines.push(`${indent(1)}types:`);
  lines.push(`${indent(2)}- strategy`);
  lines.push(`${indent(2)}- product_development`);
  lines.push(`${indent(2)}- ops_incident`);
  lines.push(`${indent(2)}- content_publish`);
  lines.push(`${indent(1)}delegation_levels:`);
  lines.push(`${indent(2)}1: { name: auto-execute, needs_meeting: false }`);
  lines.push(`${indent(2)}2: { name: execute-then-report, needs_meeting: false }`);
  lines.push(`${indent(2)}3: { name: approve-then-execute, needs_meeting: true }`);
  lines.push(`${indent(2)}4: { name: chairman-directive, needs_meeting: true }`);

  return lines.join('\n') + '\n';
}

// ── Main ──

async function main() {
  console.log('');
  console.log('╔══════════════════════════════════════════╗');
  console.log('║      create-y-company — YAML Generator   ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');
  console.log('Answer the prompts to generate your company.yml');
  console.log('Press Enter to accept [defaults]');
  console.log('');

  // ── Company basics ──
  const companyName = await ask('Company name', 'My AI Company');
  const mission = await ask('Company mission', 'Build the future with AI agents');
  const chairman = await ask('Chairman/CEO name', 'CEO');
  const language = await askChoice('Default language', ['ko', 'en'], 'ko');
  const theme = await askChoice('Theme', ['dark', 'light'], 'dark');

  // ── LLM setup ──
  console.log('');
  console.log('── LLM Setup ──');
  console.log('  1) ollama-only  — All local models (free, needs GPU)');
  console.log('  2) cloud-only   — Claude + Gemini (needs API keys)');
  console.log('  3) hybrid       — Mix of local + cloud');
  const llmChoice = await askChoice('LLM preset', ['ollama-only', 'cloud-only', 'hybrid'], 'hybrid');
  const llms = LLM_PRESETS[llmChoice];

  // ── Departments ──
  console.log('');
  console.log('── Departments ──');
  const deptCount = await askNumber('How many departments?', 3);
  const departments: Department[] = [];

  for (let i = 0; i < deptCount; i++) {
    console.log(`\n  Department ${i + 1}/${deptCount}:`);
    const nameEn = await ask('  Name (English)', `Department ${i + 1}`);
    const nameKo = await ask('  Name (Korean)', nameEn);
    const floor = await askNumber('  Floor number', deptCount - i);
    const id = nameEn.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
    departments.push({
      id,
      name_en: nameEn,
      name_ko: nameKo,
      floor,
      short_en: nameEn.split(' ')[0],
      short_ko: nameKo.split(' ')[0],
    });
  }

  // ── Agents ──
  console.log('');
  console.log('── Agents ──');
  const agentCount = await askNumber('How many agents?', 5);
  const agents: Agent[] = [];

  const llmKeys = Object.keys(llms);
  const tiers = ['C', 'Director', 'Manager', 'Staff'];
  const roles = ['analyst', 'reviewer', 'executor', 'synthesizer', 'strategist'];
  const deptIds = departments.map((d) => d.id);

  for (let i = 0; i < agentCount; i++) {
    console.log(`\n  Agent ${i + 1}/${agentCount}:`);
    const name = await ask('  Agent name', `Agent${i + 1}`);
    const deptPrompt = deptIds.length > 0 ? ` (${deptIds.join('/')})` : '';
    const department = await ask(`  Department${deptPrompt}`, deptIds[0] || 'general');
    const tier = await askChoice('  Tier', tiers, i === 0 ? 'Director' : 'Manager');
    const role = await askChoice('  Role', roles, 'executor');

    const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '');
    agents.push({
      id,
      number: String(i + 1).padStart(2, '0'),
      name,
      tier,
      department: deptIds.includes(department) ? department : deptIds[0] || department,
      reportTo: i === 0 ? 'chairman' : agents[0].id,
      llm: llmKeys[i % llmKeys.length],
      role,
      skills: [`${role}-tasks`, 'general'],
    });
  }

  // ── Generate ──
  console.log('');
  console.log('Generating company.yml...');

  const yaml = generateYaml({
    companyName,
    mission,
    chairman,
    language,
    theme,
    llms,
    departments,
    agents,
  });

  const outPath = path.resolve(process.cwd(), 'company.yml');
  fs.writeFileSync(outPath, yaml, 'utf-8');

  console.log('');
  console.log(`✅ Created: ${outPath}`);
  console.log(`   ${departments.length} departments, ${agents.length} agents, ${llmKeys.length} LLMs`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Review and edit company.yml as needed');
  console.log('  2. Run: npm run dev');
  console.log('  3. Your AI company is live! 🏢');
  console.log('');

  rl.close();
}

main().catch((err) => {
  console.error('Error:', err);
  rl.close();
  process.exit(1);
});
